#server:
# port: 8080
 
spring:
 h2:
  console:
   enabled: true
   
 mvc:
  view:
   prefix: /WEB-INF/jsp/templates/
   suffix: .jsp
   
 resources:
  chain:
   strategy:
    content:
     enabled: true
     paths: /**     
     
 profiles:
    active: local #기본환경선택
 jpa: 
   properties:
     hibernate:
       dialect: org.hibernate.dialect.MySQL5InnoDBDialect
    
# local 환경
---
spring:
  profiles: local
  datasource:
    data: classpath:data-h2.sql # 시작할때 실행시킬 script
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create-drop
  h2:
    console:
      enabled: true
      
# 운영 환경
---
spring.profiles: set1
spring.profiles.include: real-db

server:
  port: 8081

---
spring.profiles: set2
spring.profiles.include: real-db

server:
  port: 8082      